spring:
  datasource:
    url: jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:minimal.sql
      continue-on-error: true
      encoding: UTF-8
      schema-locations: # explicitly set to empty to avoid conflicts
      
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
        web-admin-password: admin

# Security configuration
server:
  port: 9007
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# Logging configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.boot.sql.init: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

# JWT Configuration (if needed)
jwt:
  secret: your-secret-key-here
  expiration: 86400000  # 24 hours in milliseconds
